from helium.api import *
from selenium import webdriver
import getpass
import time

pswd = getpass.getpass()
email = input("enter an email")

start_chrome()
go_to("up816571.myvm.port.ac.uk")
click("Sign in")
write(email)
press(ENTER)
time.sleep(1)
write(pswd)
press(ENTER)
time.sleep(3)
click("New session")
write("Test")
press(TAB)
write("16")
write("03")
write("2018")
press(TAB)
write("12")
write("30")
press(TAB)
press(TAB)
press(TAB)
time.sleep(1)
press(ENTER)
time.sleep(3)
click("New session")
time.sleep(1)
write("", into="title")
press(TAB)
write("16")
write("03")
write("2018")
press(TAB)
write("12")
write("30")
press(TAB)
press(TAB)
press(TAB)
time.sleep(1)
press(ENTER)
time.sleep(1)
write("A Really Long Test String Over 20", into="title")
time.sleep(1)
click("Submit")
time.sleep(1)
click("New session")
write("Test2", into="title")
press(TAB)
press(TAB)
write("03")
write("2018")
press(TAB)
write("12")
write("30")
press(TAB)
press(TAB)
press(TAB)
time.sleep(1)
press(ENTER)
#click("Test2")
#press(TAB) 
#write("03")
#press(TAB)
#press(TAB)
#write("")
#click("sibmit")