from helium.api import *
import getpass
import time

pswd = getpass.getpass()
email = input("enter an email ")

start_chrome()
go_to("up816571.myvm.port.ac.uk")
click("Sign in")
write(email)
press(ENTER)
time.sleep(2)
write(pswd)
press(ENTER)
time.sleep(3)
click("New session")
write("Test")
press(TAB)
write("16032018")
press(TAB)
write("1230")
press(TAB)
press(TAB)
press(TAB)
time.sleep(1)
press(ENTER)
time.sleep(1)
click("New session")
time.sleep(1)
write("", into="title")
press(TAB)
write("16032018")
press(TAB)
write("1230")
press(TAB)
press(TAB)
press(TAB)
time.sleep(1)
press(ENTER)
time.sleep(1)
write("A Really Long Test String Over 20", into="title")
time.sleep(1)
click("Submit")
time.sleep(1)
click("New session")
write("Test2", into="title")
press(TAB)
press(TAB)
write("032018")
press(TAB)
write("1230")
press(TAB)
press(TAB)
press(TAB)
time.sleep(1)
press(ENTER)
time.sleep(1)
click("Go Back")
time.sleep(1)
click("New session")
write("Test2", into="title")
press(TAB)
write("16032018")
press(TAB)
press(TAB)
write("30")
press(TAB)
press(TAB)
press(TAB)
time.sleep(1)
press(ENTER)
time.sleep(1)
click("Go Back")
time.sleep(1)
click("New session")
write("Test3", into="title")
press(TAB)
write("16032018")
press(TAB)
write("1230")
press(TAB)
write("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante.")
press(TAB)
press(TAB)
time.sleep(1)
press(ENTER)
time.sleep(1)
click("New session")
time.sleep(3)
write("Test4", into="title")
press(TAB)
write("16032018")
press(TAB)
write("1230")
press(TAB)
click(RadioButton("Deadline"))
press(TAB)
time.sleep(1)
press(ENTER)
time.sleep(1)
kill_browser()